test_that("do_notional_prep_noprep", {
  out <- do_notional_prep_noprep(.notional = notional_tst)
  out_prep <- out$notional_prep
  out_noprep <- out$notional_noprep
  expect_equal(nrow(out_prep), 69120)
  expect_equal(nrow(out_noprep), 37920)
  expect_equal(out_prep %>% distinct(COD_VALUTA_FINALE) %>% pull(), "EUR")
  expect_equal(out_noprep %>% distinct(COD_VALUTA_FINALE) %>% pull(), c("EUR", "GBP", "JPY", "USD"))
  expect_equal(out_prep %>% distinct(COD_ENTITY) %>% pull(), c("ABU",
                                                               "ACA",
                                                               "AMS",
                                                               "BALEX",
                                                               "BIB",
                                                               "BIR",
                                                               "CIB",
                                                               "DBA",
                                                               "DUB",
                                                               "FIDEU",
                                                               "FRA",
                                                               "HKG",
                                                               "ISBA",
                                                               "ISH",
                                                               "ISPBR",
                                                               "ISPRO",
                                                               "IST",
                                                               "ITB",
                                                               "LND",
                                                               "MDR",
                                                               "NYK",
                                                               "PBZBH",
                                                               "PBZKO",
                                                               "PBZPZ",
                                                               "PIT",
                                                               "PRAV",
                                                               "PRG",
                                                               "PRV",
                                                               "SEB",
                                                               "SHA",
                                                               "SIN",
                                                               "SPIMI",
                                                               "SYD",
                                                               "TOK",
                                                               "VRS",
                                                               "VUB"))
  expect_equal(out_noprep %>% distinct(COD_ENTITY) %>% pull(), c("DOH",
                                                                 "VBM",
                                                                 "AMS",
                                                                 "BALEX",
                                                                 "BIB",
                                                                 "BIR",
                                                                 "CIB",
                                                                 "DBA",
                                                                 "DUB",
                                                                 "FIDEU",
                                                                 "FRA",
                                                                 "HKG",
                                                                 "ISBA",
                                                                 "ISPRO",
                                                                 "LND",
                                                                 "MDR",
                                                                 "NYK",
                                                                 "PBZBH",
                                                                 "PBZKO",
                                                                 "PBZPZ",
                                                                 "PRG",
                                                                 "SEB",
                                                                 "SIN",
                                                                 "SPIMI",
                                                                 "TOK",
                                                                 "VRS",
                                                                 "VUB",
                                                                 "SHA",
                                                                 "ABU",
                                                                 "ISPBR",
                                                                 "IST",
                                                                 "PRAV",
                                                                 "SYD"))
  expect_equal(sum(out_prep$VAL_NOTIONAL), 49907053802)
  expect_equal(sum(out_noprep$VAL_NOTIONAL), 8376179325)

})
